### ISSUE TITLE
The big autocrafting todo

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1800]
- [x] Get regular recipes to work again
- [x] Get processing recipes to work again
- [x] Fix the Crafting Monitor
- [x] Resizable crafting monitor
- [x] Task cancelling
- [x] Recursion check
- [x] Oredict
- [x] Pattern chains
- [x] Crafting task persistance
