### ISSUE TITLE
Todo for the wiki for 1.6

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#1876]
This is a tracking issue for myself.

- [x] Finish remaining pages
- [x] Covers
- [x] Update "deleted in" badge for 1.6 removals
- [x] Update "added in" badge for 1.6 additions
- [x] Re-export all renders
- [x] /createdisk and disk / storage block ID
