### ISSUE TITLE
Stuff todo for next release

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#249]
- [x] Re-add crafting monitor syncing
- [x] Check why inventories aren't dropped when a cable part is a microblock
- [x] Test if MC doesn't crash without IC2 / JEI / Tesla
- [x] Make MCMultiPart a hard requirement, see if it doesn't crash but display an error message instead
- [x] Test on a server (gui sync: storage count, priority etc)
- [x] Test if inv patch works
- [x] Add shiftclick handler for containerstorage
- [x] Use dataparam on ext storage
- [x] Do the 2 mcmultipart PR's, fix canProvidePower being true
