### ISSUE TITLE
New crafting system todo

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#433]
- [x] use IItemStackList for toTake
- [x] processable crafting monitor element
- [x] re-implement fluid autocrafting
- [x] oredict patterns
- [x] make oredict patterns give back correct byproduct
- [x] give back items on cancel
- [x] fix damage bugs
- [x] fix oredict using wrong items (1 spruce wood uses 4 regular planks for example)
- [x] send crafting monitor updates
- [x] persistance
- [x] machines in use
- [x] no machine found
- [x] crafting preview
- [x] add button in gui to toggle oredict crafting
- [x] threaded calc, disable start btn
- [x] fix tooltips in crafting monitor
- [x] fix not updating always crafting monitor state
- [x] fix broken serialization for processables
- [x] oredict checkbox dissapearing in grid
- [x] loads of testing

**Comment by Jumap211** [comment]
While you're creating the new system, would it be possible that the crafting system accept non-stackable items ? Currently, if the craft involves à non-stackable item, the non stackable item will be crafted but the craft which needs it will can't use it. For example with the energy tablets from mekanism, any craft which needs them can't be done but all parts of the craft will be

**Comment by Californ1a** [comment]
It'd also be sweet if the new crafting system supported using a machine that it already in-use if that machine can take multiple inputs (i.e. Mekanism's [factory machines](http://wiki.aidancbrady.com/wiki/Factory)). I know I have a ton of patterns set up for smelting stuff and a Mekanism factory sounded like a great space-saver vs using a ton of separate furnaces, but it seems the crafting system never inputs to the second slot unless it's doing more than a stack of the same type of item.

**Comment by choekstr** [comment]
@Californ1a You just need to turn on auto-sort and it will spread out the incoming and RS can continue to dump more items into the Mekanism factory.

**Comment by Sorbe** [comment]
You may also have issues with patterns that double inputs ( one iron ingot => two iron ingots ).
Another similar problem with patterns where the input changes slightly (  383:4  => 384:5 ).

**Comment by Californ1a** [comment]
@choekstr I mean with multiple different item types (say you're smelting iron ore, sand, and cobble all at once), rather than greater than a stack of single item type. I know auto-sort on the Mekanism factories will split large quantities of the same type of item into the different input slots, but if you're trying to smelt both iron and glass (with auto-sort off, meaning you have open input slots), then RS will think the machine is in-use, making it wait for all of a single item type to finish before inserting the next type. Basically, if there's an open input slot on a machine, then it shouldn't be tagged as in-use by RS.

**Comment by Darkere** [comment]
I'm wondering if we will have to make new patterns for this update?

**Comment by raoulvdberge** [comment]
No, you won't.

**Comment by seiverdamross** [comment]
how about a blocking mode from AE2. so it will only push one set of items at once

**Comment by raoulvdberge** [comment]
Done
