### ISSUE TITLE
TODO for 1.4

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#820]
- [ ] Fix energy bug in Reader/Writers
- [ ] Try to fix some more crashes?
- [ ] Fix bugs remaining on the issue tracker
- [ ] Test on server
- [ ] Crafter tiers
- [ ] Artwork

**Comment by Joshwoo70** [comment]
[  ] try and implement upgrade slots modularity.

**Comment by FancyBanana** [comment]
Collaborate with other mod creators for interoperability? I would be grate if your mod had integration with enderIO (like AE2) and OpenComputers support (like AE2).

**Comment by raoulvdberge** [comment]
This issue is dumb

**Comment by way2muchnoise** [comment]
lol
